# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-13 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rettiwt', '0004_auto_20170913_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likable',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Likable',
        ),
    ]
