language: python

python:
  - 3.6.2

service:
  - postgresql

before_script:
  - psql -c 'create database test_web_2;' -U postgres

script:
  - pytest

deploy:
  provider: heroku

  api_key: ${HEROKU_API_KEY}
  app: technotrack-rettiwt

  on:
    branch: master