language: python

python:
  - 3.6.2

service:
  - postgresql

before_script:
  - psql -c 'create database test;' -U postgres
  - ./manage.py migrate

env:
  - DATABASE_URL="postgres://postgres:@localhost:5432/test"

script:
  - pytest

deploy:
  provider: heroku

  api_key: ${HEROKU_API_KEY}
  app: technotrack-rettiwt

  on:
    branch: master