language: python

python:
  - 3.6.2

script:
  - pytest

deploy:
  provider: heroku

  api_key: ${HEROKU_API_KEY}
  app: technotrack-rettiwt

  run:
    - "./migrate.py migrate"
    - restart

  on:
    branch: master