# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-24 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170924_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='feed',
            field=models.ManyToManyField(related_name='user', to='core.Event'),
        ),
    ]
