# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-24 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170924_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feed',
            field=models.ManyToManyField(related_name='users', through='core.UserEvent', to='core.Event'),
        ),
    ]
